version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/retrofitlink}
      - BLOCKCHAIN_RPC_URL=${BLOCKCHAIN_RPC_URL:-http://blockchain:8545}
      - JWT_SECRET=${JWT_SECRET:-development_jwt_secret_change_in_production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - IOT_API_KEY=${IOT_API_KEY:-development_iot_api_key}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY:-development_internal_api_key}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    depends_on:
      - mongo
      - blockchain
    volumes:
      - ./backend/logs:/app/logs
    restart: unless-stopped
    networks:
      - retrofitlink-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5000}
      - REACT_APP_BLOCKCHAIN_RPC_URL=${REACT_APP_BLOCKCHAIN_RPC_URL:-http://localhost:8545}
      - REACT_APP_ENVIRONMENT=${NODE_ENV:-development}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - retrofitlink-network

  blockchain:
    build: 
      context: ./blockchain
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - blockchain-data:/app/data
    restart: unless-stopped
    networks:
      - retrofitlink-network

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-changeme}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-retrofitlink}
    volumes:
      - mongo-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - retrofitlink-network

  iot-simulator:
    build: 
      context: ./iot-simulator
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://backend:5000}
      - IOT_API_KEY=${IOT_API_KEY:-development_iot_api_key}
      - SIMULATION_INTERVAL=${SIMULATION_INTERVAL:-30000}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - retrofitlink-network

volumes:
  mongo-data:
    driver: local
  blockchain-data:
    driver: local

networks:
  retrofitlink-network:
    driver: bridge
