{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "retrofitlink.backend.fullname" . }}
  labels:
    {{- include "retrofitlink.componentLabels" (dict "component" "backend" "context" .) | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "retrofitlink.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
