apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "retrofitlink.fullname" . }}-blockchain-config
  labels:
    {{- include "retrofitlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: blockchain
data:
  NETWORK_ID: "{{ .Values.blockchain.networkId }}"
  CHAIN_ID: "{{ .Values.blockchain.chainId }}"
  ACCOUNT_KEYS_PATH: "/app/data/accounts"
  MNEMONIC: "{{ .Values.blockchain.mnemonic }}"
  BLOCK_TIME: "{{ .Values.blockchain.blockTime }}"
  GAS_LIMIT: "{{ .Values.blockchain.gasLimit }}"
  GAS_PRICE: "{{ .Values.blockchain.gasPrice }}"
