{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "retrofitlink.fullname" . }}-cluster-secret-store
  labels:
    {{- include "retrofitlink.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.externalSecrets.provider "aws" }}
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region }}
      {{- if .Values.externalSecrets.aws.role }}
      role: {{ .Values.externalSecrets.aws.role }}
      {{- end }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "retrofitlink.serviceAccountName" . }}
            namespace: {{ .Release.Namespace }}
  {{- else if eq .Values.externalSecrets.provider "vault" }}
  provider:
    vault:
      server: {{ .Values.externalSecrets.vault.server }}
      path: {{ .Values.externalSecrets.vault.path }}
      version: {{ .Values.externalSecrets.vault.version | default "v2" }}
      auth:
        kubernetes:
          mountPath: {{ .Values.externalSecrets.vault.kubernetes.mountPath | default "kubernetes" }}
          role: {{ .Values.externalSecrets.vault.kubernetes.role }}
          serviceAccountRef:
            name: {{ include "retrofitlink.serviceAccountName" . }}
            namespace: {{ .Release.Namespace }}
  {{- else if eq .Values.externalSecrets.provider "gcp" }}
  provider:
    gcpsm:
      projectId: {{ .Values.externalSecrets.gcp.projectId }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecrets.gcp.clusterLocation }}
          clusterName: {{ .Values.externalSecrets.gcp.clusterName }}
          serviceAccountRef:
            name: {{ include "retrofitlink.serviceAccountName" . }}
            namespace: {{ .Release.Namespace }}
  {{- else if eq .Values.externalSecrets.provider "azure" }}
  provider:
    azurekv:
      vaultUrl: {{ .Values.externalSecrets.azure.vaultUrl }}
      {{- if .Values.externalSecrets.azure.tenantId }}
      tenantId: {{ .Values.externalSecrets.azure.tenantId }}
      {{- end }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{ include "retrofitlink.serviceAccountName" . }}
            namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
