{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "retrofitlink.fullname" . }}-external-secrets
  labels:
    {{- include "retrofitlink.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind | default "SecretStore" }}
  target:
    name: {{ include "retrofitlink.fullname" . }}-external-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "retrofitlink.labels" . | nindent 10 }}
      data:
        # Database credentials from external secret store
        {{- range .Values.externalSecrets.data }}
        {{ .name }}: "{{`{{ .{{ .remoteRef.key }} | toString }}`}}"
        {{- end }}
  data:
  {{- range .Values.externalSecrets.data }}
  - secretKey: {{ .name }}
    remoteRef:
      key: {{ .remoteRef.key }}
      {{- if .remoteRef.property }}
      property: {{ .remoteRef.property }}
      {{- end }}
      {{- if .remoteRef.version }}
      version: {{ .remoteRef.version }}
      {{- end }}
  {{- end }}
{{- end }}
