{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "retrofitlink.frontend.fullname" . }}
  labels:
    {{- include "retrofitlink.componentLabels" (dict "component" "frontend" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "retrofitlink.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
