apiVersion: v1
kind: Service
metadata:
  name: {{ include "retrofitlink.fullname" . }}-grafana
  labels:
    {{- include "retrofitlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: grafana
spec:
  type: {{ .Values.monitoring.grafana.service.type }}
  ports:
    - port: {{ .Values.monitoring.grafana.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "retrofitlink.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: grafana
