apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "retrofitlink.fullname" . }}-grafana
  labels:
    {{- include "retrofitlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: grafana
spec:
  replicas: {{ .Values.monitoring.grafana.replicaCount }}
  selector:
    matchLabels:
      {{- include "retrofitlink.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/name: grafana
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/grafana-configmap.yaml") . | sha256sum }}
        {{- with .Values.monitoring.grafana.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "retrofitlink.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/name: grafana
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "retrofitlink.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.monitoring.grafana.podSecurityContext | nindent 8 }}
      containers:
        - name: grafana
          securityContext:
            {{- toYaml .Values.monitoring.grafana.securityContext | nindent 12 }}
          image: "{{ .Values.monitoring.grafana.image.repository }}:{{ .Values.monitoring.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.monitoring.grafana.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "retrofitlink.fullname" . }}-grafana-secrets
                  key: admin-password
            - name: GF_SECURITY_ADMIN_USER
              value: "{{ .Values.monitoring.grafana.adminUser }}"
            - name: GF_PATHS_DATA
              value: /var/lib/grafana
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          livenessProbe:
            httpGet:
              path: /api/health
              port: web
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: web
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.monitoring.grafana.resources | nindent 12 }}
          volumeMounts:
            - name: storage
              mountPath: /var/lib/grafana
            - name: provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: storage
          {{- if .Values.monitoring.grafana.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "retrofitlink.fullname" . }}-grafana-storage
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: provisioning-datasources
          configMap:
            name: {{ include "retrofitlink.fullname" . }}-grafana-datasources
        - name: provisioning-dashboards
          configMap:
            name: {{ include "retrofitlink.fullname" . }}-grafana-dashboards-config
        - name: dashboards
          configMap:
            name: {{ include "retrofitlink.fullname" . }}-grafana-dashboards
      {{- with .Values.monitoring.grafana.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.monitoring.grafana.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.monitoring.grafana.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
