apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "retrofitlink.fullname" . }}-prometheus-rules
  labels:
    {{- include "retrofitlink.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: prometheus
data:
  alert_rules.yml: |
    groups:
      - name: retrofitlink.rules
        rules:
          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: High error rate detected
              description: "Error rate is {{ $value }} errors per second"
              
          - alert: HighResponseTime
            expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High response time detected
              description: "95th percentile response time is {{ $value }} seconds"
              
          - alert: PodCrashLooping
            expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: Pod is crash looping
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping"
              
          - alert: HighMemoryUsage
            expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.9
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High memory usage
              description: "Container {{ $labels.container }} is using {{ $value | humanizePercentage }} of memory"
              
          - alert: HighCPUUsage
            expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High CPU usage
              description: "Container {{ $labels.container }} is using {{ $value | humanizePercentage }} of CPU"
              
          - alert: DatabaseConnectionFailure
            expr: up{job="mongodb"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: Database connection failure
              description: "MongoDB instance is down"
              
          - alert: BlockchainNodeDown
            expr: up{job="blockchain"} == 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: Blockchain node is down
              description: "Blockchain node is not responding"
