apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retrofitlink.fullname" . }}-app-secrets
  labels:
    {{- include "retrofitlink.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials
  mongodb-username: {{ .Values.secrets.mongodb.username | b64enc | quote }}
  mongodb-password: {{ .Values.secrets.mongodb.password | b64enc | quote }}
  postgres-username: {{ .Values.secrets.postgres.username | b64enc | quote }}
  postgres-password: {{ .Values.secrets.postgres.password | b64enc | quote }}
  
  # JWT and API keys
  jwt-secret: {{ .Values.secrets.jwt.secret | b64enc | quote }}
  api-key: {{ .Values.secrets.api.key | b64enc | quote }}
  
  # Blockchain credentials
  {{- if .Values.blockchain.enabled }}
  blockchain-private-key: {{ .Values.secrets.blockchain.privateKey | b64enc | quote }}
  blockchain-mnemonic: {{ .Values.secrets.blockchain.mnemonic | b64enc | quote }}
  {{- end }}
  
  # External service credentials
  {{- if .Values.monitoring.enabled }}
  grafana-admin-password: {{ .Values.secrets.grafana.adminPassword | b64enc | quote }}
  {{- end }}
  
  # IoT device credentials
  {{- if .Values.iotSimulator.enabled }}
  iot-device-token: {{ .Values.secrets.iot.deviceToken | b64enc | quote }}
  {{- end }}
  
  # SSL/TLS certificates (if provided)
  {{- if .Values.secrets.tls.enabled }}
  tls-cert: {{ .Values.secrets.tls.cert | b64enc | quote }}
  tls-key: {{ .Values.secrets.tls.key | b64enc | quote }}
  {{- end }}
